AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an EC2 instance in a specific VPC'

Parameters:
  VpcId:
    Type: String
    Default: vpc-0cb8773460c4c5af2
    Description: VPC ID for the EC2 instance
  VpcSubnetId:
    Type: String
    Default: subnet-008f1f80a467cd6a6
    Description: Subnet ID for the EC2 instance

Resources:
  EC2SSMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: /

  EC2SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2SSMRole

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0cf4768e2f1e520c5
      # SubnetId: subnet-06b6d098bb30c6c97
      InstanceType: t3.micro
      IamInstanceProfile: !Ref EC2SSMInstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref VpcSubnetId
          DeleteOnTermination: true
          GroupSet:
            - !GetAtt InstanceSecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: MyEC2Instance
      # SecurityGroupIds:
      #   - !GetAtt InstanceSecurityGroup.GroupId

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      GroupName: MyInstanceSecurityGroup
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
  PrivateIp:
    Description: Private IP address
    Value: !GetAtt EC2Instance.PrivateIp
    