AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an EC2 instance in a specific VPC'

Parameters:
  VpcId:
    Type: String
    Default: vpc-08c34277a85be22be
    Description: VPC ID for the EC2 instance
  VpcSubnetId:
    Type: String
    Default: subnet-097c9986bbc3882a4
    Description: Subnet ID for the EC2 instance

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0cf4768e2f1e520c5
      InstanceType: t3.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref VpcSubnetId
          DeleteOnTermination: true
          GroupSet:
            - !GetAtt InstanceSecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: MyEC2Instance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Update the system
          dnf update -y

          # Install Apache (httpd) - Amazon Linux 2023 uses dnf
          dnf install -y httpd

          # Enable and start Apache
          systemctl enable httpd
          systemctl start httpd

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      GroupName: MyInstanceSecurityGroup
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
  PrivateIp:
    Description: Private IP address
    Value: !GetAtt EC2Instance.PrivateIp
    