#!/usr/bin/env bash

## create the vpc (Note that the create vpc command is used with ec2, not with vpc)
VPC_ID=$(aws ec2 create-vpc \
    --cidr-block "172.16.1.0/16" \
    --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=My-cli-VPC}]' \
    --query 'Vpc.VpcId' \
    --output text)

echo "VPC ID: $VPC_ID"

## create the IGW
IGW_ID=$(aws ec2 create-internet-gateway \
    --tag-specifications 'ResourceType=internet-gateway,Tags=[{Key=Name,Value=My-cli-IGW}]' \
    --query 'InternetGateway.InternetGatewayId' \
    --output text)

echo "IGW ID: $IGW_ID"
 
## attach the IGW to the vpc
aws ec2 attach-internet-gateway \
    --internet-gateway-id $IGW_ID \
    --vpc-id $VPC_ID

## create a new subnet

SUBNET_ID=$(aws ec2 create-subnet \
    --vpc-id $VPC_ID \
    --cidr-block "172.16.1.0/24" \
    --query Subnet.SubnetId \
    --output text)

echo "Subnet ID: $SUBNET_ID"

## modify the subnet to enable auto-assign public IP addresses on launch
aws ec2 modify-subnet-attribute \
    --subnet-id $SUBNET_ID \
    --map-public-ip-on-launch

## create a route table and explicitly associate the subnet with the route table

ROUTE_TABLE_ID=$(aws ec2 create-route-table \
    --vpc-id $VPC_ID \
    --query 'RouteTable.RouteTableId' \
    --output text)

echo "Route Table ID: $ROUTE_TABLE_ID"

aws ec2 associate-route-table \
    --route-table-id $ROUTE_TABLE_ID \
    --subnet-id $SUBNET_ID

## add a route for the route table to the IGW
aws ec2 create-route \
    --route-table-id $ROUTE_TABLE_ID \
    --destination-cidr-block "0.0.0.0/0" \
    --gateway-id $IGW_ID