AWSTemplateFormatVersion: '2010-09-09'

Resources:

  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ecs-demo
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE

Outputs:

  RepositoryUri:
    Value: !GetAtt ECRRepository.RepositoryUri
