#! /usr/bin/bash

if [ -z "$1" ]; then
    echo "First argument is missing"
    exit 1
else
    echo "First argument exists: $1"
fi

DESTINATION_BUCKET=${2:-11ck012588}

aws s3 sync "$1" "s3://$DESTINATION_BUCKET"