#!/usr/bin/bash

# build the docker image
docker build -t lambda-container-example .

# tag the docker image
docker tag lambda-container-example:latest 492534223967.dkr.ecr.eu-central-1.amazonaws.com/lambda-container-example:latest

# login
aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 492534223967.dkr.ecr.eu-central-1.amazonaws.com

# push the docker image to ECR
docker push 492534223967.dkr.ecr.eu-central-1.amazonaws.com/lambda-container-example:latest

