Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: docker
      DockerContext: ./
      Dockerfile: Dockerfile
    Properties:
      PackageType: Image
      ImageUri: 492534223967.dkr.ecr.eu-central-1.amazonaws.com/lambda-container-example:latest
      ImageConfig:
        Command:
          - "index.handler"
      MemorySize: 128
      Timeout: 30
      
