AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket + minimal EC2 instance in eu-central-1

Parameters:
  LatestAmiId:
    Description: Latest Amazon Linux 2 AMI ID
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
  
  S3Bucket:
    Type: AWS::S3::Bucket
